### ISSUE TITLE
Breaking with SMAD4 sequence in 2022 and 2024 JASPAR releases

### ISSUE THREAD

**Issue by ievarau** [wassermanlab/JASPAR-inference-tool#9]
Hello,

we have identified that inference tool breaks with SMAD4 protein sequence in 2022 and 2024 releases of JASPAR. 2020 seems to be working. I have tried running the inference using environment and specific versions of this repo, so I can see what is the error. I will post the output.

**SMAD4 protein sequence I used:**
MDNMSITNTPTSNDACLSIVHSLMCHRQGGESETFAKRAIESLVKKLKEKKDELDSLITAITTNGAHPSKCVTIQRTLDGRLQVAGRKGFPHVIYARLWRWPDLHKNELKHVKYCQYAFDLKCDSVCVNPYHYERVVSPGIDLSGLTLQSNAPSMLVKDEYVHDFEGQPSLPTEGHSIQTIQHPPSNRASTETYSAPALLAPAESNATSTTNFPNIPVASTSQPASILAGSHSEGLLQIASGPQPGQQQNGFTAQPATYHHNSTTTWTGSRTAPYTPNLPHHQNGHLQHHPPMPPHPGHYWPVHNELAFQPPISNHPAPEYWCSIAYFEMDVQVGETFKVPSSCPVVTVDGYVDPSGGDRFCLGQLSNVHRTEAIERARLHIGKGVQLECKGEGDVWVRCLSDHAVFVQSYYLDREAGRAPGDAVHKIYPSAYIKVFDLRQCHRQMQQQAATAQAAAAAQAAAVAGNIPGPGSVGGIAPAISLSAAAGIGVDDLRRLCILRMSFVKGWGPDYPRQSIKETPCWIEIHLHRALQLLDEVLHTMPIADPQPLD

**Running with commit used in 2020:**
```
HEAD is now at faa66049 Update infer_profile.py

(inference) [ievarau@biotin3 JASPAR-inference-tool]$ ./infer_profile.py --fasta-file ./examples/smad.fa --files-dir ./files/ --models-dir ./models/ --latest

0it [00:00, ?it/s]
Query	TF Name	TF Matrix	E-value	Query Start-End	TF Start-End	DBD %ID	Similarity Regression
```

**Running with commit used in 2022:**
```
(inference) [ievarau@biotin3 JASPAR-inference-tool]$ git checkout "5fa64a79c79763384b484d9345bf112bd7dcbf11"

Updating files: 100% (4967/4967), done.
Previous HEAD position was faa66049 Update infer_profile.py
HEAD is now at 5fa64a79 changed modes

(inference) [ievarau@biotin3 JASPAR-inference-tool]$ ./infer_profile.py --latest ./examples/smad.fa

Traceback (most recent call last):
  File "./infer_profile.py", line 661, in <module>
    main()
  File "./infer_profile.py", line 88, in main
    args.output_file, args.threads, args.latest, args.rost, args.taxon)
  File "./infer_profile.py", line 123, in infer_profiles
    pool = Pool(min([threads, len(seq_records)]))
  File "/div/pythagoras/u2/ievarau/micromamba/envs/inference/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/div/pythagoras/u2/ievarau/micromamba/envs/inference/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Running with jaspar-2024 tag:**
```
(inference) [ievarau@biotin3 JASPAR-inference-tool]$ git checkout "jaspar-2024"

Updating files: 100% (2774/2774), done.
Previous HEAD position was 5fa64a79 changed modes
HEAD is now at 4b852a51 check pfam version

(inference) [ievarau@biotin3 JASPAR-inference-tool]$ ./infer_profile.py --latest ./examples/smad.fa

Traceback (most recent call last):
  File "./infer_profile.py", line 662, in <module>
    main()
  File "./infer_profile.py", line 88, in main
    args.output_file, args.threads, args.latest, args.rost, args.taxon)
  File "./infer_profile.py", line 123, in infer_profiles
    pool = Pool(min([threads, len(seq_records)]))
  File "/div/pythagoras/u2/ievarau/micromamba/envs/inference/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/div/pythagoras/u2/ievarau/micromamba/envs/inference/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by ievarau** [comment]
I am updating the issue. It actually works. The input requires to have fasta headers. Once I adjusted the input file, it worked. However, on JASPAR website the sequences are pasted without header and then the tool does not work. Example sequence though works

**Comment by oriolfornes** [comment]
When Aziz incorporated my code to the website, I created the following function:

```
def infer_SeqRecord_profiles(seq_record, cisbp, jaspar, dummy_dir="/tmp/",
    files_dir="./files/", latest=False, n=5, taxons=["fungi", "insects",
    "nematodes", "plants", "vertebrates"]):
```

From the JASPAR website you need to create a [`SeqRecord`](https://biopython.org/wiki/SeqRecord), and then pass it to this function. The `cisbp` and `jaspar` objects are uploaded as follows: 

```
 # Load data
 cisbp = __load_CisBP_models(files_dir)
 jaspar = __load_JASPAR_files_n_models(files_dir, taxons)
```

Let me know if this helps.
